AmigoInvisible/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('', include('sorteos.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

sorteos/urls.py
from django.urls import path

from . import views

app_name = 'sorteos'
urlpatterns = [
    path('', views.LandingView.as_view(), name='landing'),
    path('amin', views.IndexView.as_view(), name='index'),
    path('sorteo/', views.SorteoView.as_view(), name='sorteo'),
    path('sorteo/<slug:md5>/', views.DetailView.as_view(), name='detail'),
    path('sortear/<slug:md5>/', views.SortearView.as_view(), name='sortear'),
    path('mails/<slug:md5>/', views.EnviarMailsView.as_view(), name='mails'),
    path('participante/<slug:md5>/', views.ParticipanteView.as_view(), name='participante'),
    path('participanteborrar/<slug:md5>/', views.BorrarParticipanteView.as_view(), name='participanteborrar'),
    path('sorteoborrar/<slug:md5>/', views.BorrarSorteoView.as_view(), name='sorteoborrar'),
    path('exclusion/<slug:sorteo_md5>/<slug:participante_md5>/', views.ExclusionView.as_view(), name='exclusion'),
    path('exclusionborrar/<slug:md5>/', views.BorrarExclusionView.as_view(), name='exclusionborrar'),
    path('register/',views.RegisterView.as_view(), name = 'register'),
    path('activate/<uidb64>/<token>/',views.ActivateView.as_view(), name='activate'),
    path('about/', views.AboutView.as_view(), name='about'),
]

sorteos/models.py
from django.db import models
from django.conf import settings
import datetime

# Create your models here.
class Sorteo(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=200, blank=True)
    mensaje = models.TextField(max_length=500, blank=True)
    ownername = models.CharField(max_length=200, blank=False)
    created = models.DateTimeField(auto_now_add=True)
    md5 = models.SlugField(default='', max_length=32)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    done = models.BooleanField(default=False)
    enviado = models.BooleanField(default=False)

    def __str__(self):
        return self.name


class Participante(models.Model):
    sorteo = models.ForeignKey(Sorteo, on_delete=models.CASCADE)
    name = models.CharField(max_length=20)
    email = models.EmailField(blank=False)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    md5 = models.SlugField(default='', max_length=32)
    
    def __str__(self):
        return self.name


class Exclusion(models.Model):
    sorteo = models.ForeignKey(Sorteo, on_delete=models.CASCADE)
    de_participante = models.ForeignKey(Participante, on_delete=models.CASCADE, related_name='de_participante')
    a_participante = models.ForeignKey(Participante, on_delete=models.CASCADE, related_name='a_participante')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    md5 = models.SlugField(default='', max_length=32)
    
    def __str__(self):
        return self.de_participante.name + ' no puede regalar a ' + self.a_participante.name + ' en ' + self.sorteo.name


class Regalo(models.Model):
    sorteo = models.ForeignKey(Sorteo, on_delete=models.CASCADE)
    de_participante = models.ForeignKey(Participante, on_delete=models.CASCADE, related_name='de_regalante')
    a_participante = models.ForeignKey(Participante, on_delete=models.CASCADE, related_name='a_regalante')
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    created = models.DateTimeField(auto_now_add=True)
    md5 = models.SlugField(default='', max_length=32)
    
    def __str__(self):
        return self.de_participante.name + ' regala a ' + self.a_participante.name + ' en ' + self.sorteo.name

sorteos/forms.py
from hashlib import md5
from django.forms import ModelForm, EmailField
from .models import Sorteo, Participante, Exclusion
from django.shortcuts import get_object_or_404
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
    email = EmailField()
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class SorteoForm(ModelForm):
    class Meta:
        model = Sorteo
        fields = ['name', 'description', 'mensaje', 'ownername']

    def __init__(self, *args, **kwargs):
        super(SorteoForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'id': 'name', 'class':'form-control','placeholder': 'Name'})
        self.fields['ownername'].widget.attrs.update({'id': 'ownername', 'class':'form-control', 'placeholder': 'Tu nombre'})
        self.fields['description'].widget.attrs.update({'id': 'description',  'class':'form-control','placeholder': 'Description'})
        self.fields['mensaje'].widget.attrs.update({'id': 'mensaje', 'class':'form-control', 'placeholder': 'Si quieres, puedes escribir un mensaje para los participantes'})


class ParticipanteForm(ModelForm):
    class Meta:
        model = Participante
        fields = ['name', 'email']

    def __init__(self, *args, **kwargs):
        super(ParticipanteForm, self).__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'id': 'name', 'class':'form-control', 'placeholder': 'Name'})
        self.fields['email'].widget.attrs.update({'id': 'email', 'class':'form-control', 'placeholder': 'Email'})


class ExclusionForm(ModelForm):
    
    class Meta:
        model = Exclusion
        fields = ['a_participante']

    def __init__(self, sorteo_md5, participante_md5, *args, **kwargs):
        super(ExclusionForm, self).__init__(*args, **kwargs)
        self.fields['a_participante'].queryset = Participante.objects.filter(sorteo__md5=sorteo_md5).exclude(md5=participante_md5)
        self.fields['a_participante'].widget.attrs.update({'class': 'form-control'})
        

sorteos/views.py
from distutils.log import INFO
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic
from django.urls import reverse
from .models import Regalo, Sorteo, Participante, Exclusion
from .forms import SorteoForm, ParticipanteForm, ExclusionForm, RegisterForm
from datetime import datetime
import os,logging, hashlib
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.template.loader import render_to_string
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.http import HttpResponse
from .random_pairs import element, random_pairs


logger = logging.getLogger(__name__)
UserModel = get_user_model()

# Create your views here.
class IndexView(LoginRequiredMixin, generic.ListView):
    template_name = 'sorteos/index.html'
    context_object_name = 'user_sorteos_list'
    model = Sorteo
    #paginate_by = 10  # if pagination is desired
    ordering = ['-created']

    def get_queryset(self):
        return super().get_queryset().filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['version'] = settings.VERSION
        return context

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        

class SorteoView(LoginRequiredMixin, generic.View):

    def get(self, request):
        form = SorteoForm()
        ctx = {'form': form, 'version': settings.VERSION}
        return render(request, 'sorteos/sorteo.html', ctx)

    def post(self, request):
        form = SorteoForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form, 'version': settings.VERSION}
            return render(request, 'sorteos/sorteo.html', ctx)
        new_sorteo = form.save(commit=False)
        md5_string = str(datetime.now().timestamp()) + new_sorteo.name
        new_sorteo.md5 = hashlib.md5(md5_string.encode()).hexdigest()
        new_sorteo.owner = self.request.user
        new_sorteo.save()
        new_participante = Participante()
        new_participante.name = new_sorteo.ownername
        new_participante.sorteo = new_sorteo
        new_participante.email = new_sorteo.owner.email
        new_participante.owner = new_sorteo.owner
        md5_string = str(datetime.now().timestamp()) + new_sorteo.md5 + new_participante.email
        new_participante.md5 = hashlib.md5(md5_string.encode()).hexdigest()
        new_participante.save()
        log_msg = "Nuevo evento {} creado por usuario {}".format(new_sorteo.name, self.request.user)
        logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:index'))


class DetailView(LoginRequiredMixin, generic.ListView):
    template_name = 'sorteos/detail.html'
    context_object_name = 'sorteo_participantes_list'
    model = Participante
    #paginate_by = 10  # if pagination is desired
    ordering = ['-created']

    def get_queryset(self):
        self.sorteo = get_object_or_404(Sorteo,md5=self.kwargs['md5'])
        return super().get_queryset().filter(owner=self.request.user).filter(sorteo=self.sorteo)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sorteo']=self.sorteo
        exclusiones = Exclusion.objects.filter(sorteo__md5 = self.sorteo.md5)
        context['exclusiones'] = exclusiones
        context['version'] = settings.VERSION
        return context

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)


class ParticipanteView(LoginRequiredMixin, generic.View):

    def get(self, request, md5):
        form = ParticipanteForm()
        form.sorteo = get_object_or_404(Sorteo, md5=md5)
        ctx = {'form': form, 'sorteo': form.sorteo, 'version': settings.VERSION}
        return render(request, 'sorteos/participante.html', ctx)

    def post(self, request, md5):
        form = ParticipanteForm(request.POST)
        if not form.is_valid():
            form.sorteo = get_object_or_404(Sorteo, md5=md5)
            ctx = {'form': form, 'sorteo': form.sorteo, 'version': settings.VERSION}
            return render(request, 'sorteos/participante.html', ctx)
        new_participante = form.save(commit=False)
        new_participante.owner = self.request.user
        sorteo = get_object_or_404(Sorteo, md5=md5)
        new_participante.sorteo = sorteo
        md5_string = str(datetime.now().timestamp()) + md5 + new_participante.email
        new_participante.md5 = hashlib.md5(md5_string.encode()).hexdigest()
        new_participante.save()
        sorteo.done = False
        sorteo.enviado = False
        sorteo.save()
        log_msg = "Nuevo amigo {} añadido por {} en evento {}".format(new_participante.name, self.request.user,sorteo.name)
        logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:detail',kwargs={'md5':md5} ))


class ExclusionView(LoginRequiredMixin, generic.View):

    def get(self, request, sorteo_md5, participante_md5 ):
        form = ExclusionForm(sorteo_md5, participante_md5)
        form.sorteo = get_object_or_404(Sorteo, md5=sorteo_md5)
        form.de_participante = get_object_or_404(Participante,md5=participante_md5)
        exclusiones = Exclusion.objects.filter(de_participante__md5 = participante_md5)
        ctx = {'form': form, 'sorteo': form.sorteo, 'participante': form.de_participante, 'exclusiones': exclusiones, 'version': settings.VERSION}
        return render(request, 'sorteos/exclusion.html', ctx)

    def post(self, request, sorteo_md5, participante_md5):
        for e in Exclusion.objects.filter(de_participante__md5 = participante_md5):
            e.delete()
        form = ExclusionForm(sorteo_md5, participante_md5,request.POST)
        sorteo = get_object_or_404(Sorteo, md5=sorteo_md5)
        form.sorteo = sorteo
        form.de_participante = get_object_or_404(Participante,md5=participante_md5)
        if not form.is_valid():
            ctx = {'form': form, 'sorteo': form.sorteo, 'participante':form.de_participante, 'version': settings.VERSION}
            return render(request, 'sorteos/exclusion.html', ctx)
        new_exclusion = form.save(commit=False)
        new_exclusion.owner = self.request.user
        new_exclusion.sorteo = get_object_or_404(Sorteo, md5=sorteo_md5)
        new_exclusion.de_participante = get_object_or_404(Participante, md5=participante_md5)
        md5_string = str(datetime.now().timestamp()) + sorteo_md5 + participante_md5 + new_exclusion.a_participante.md5
        new_exclusion.md5 = hashlib.md5(md5_string.encode()).hexdigest()
        new_exclusion.save()
        sorteo.done = False
        sorteo.enviado = False
        sorteo.save()
        log_msg = "Nueva exclusion creada: {}".format(new_exclusion)
        logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:detail',kwargs={'md5':sorteo_md5} ))


class BorrarParticipanteView(LoginRequiredMixin, generic.View):

    def get(self, request, md5):
        participante = get_object_or_404(Participante, md5=md5)
        sorteo = get_object_or_404(Sorteo,md5=participante.sorteo.md5)
        if participante:
            participante.delete()
            sorteo.done = False
            sorteo.enviado = False
            sorteo.save()
            log_msg = "Amigo {} borrado por {} de evento {}".format(participante.name, self.request.user,sorteo.name)
            logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:detail',kwargs={'md5':sorteo.md5} ))


class BorrarExclusionView(LoginRequiredMixin, generic.View):

    def get(self, request, md5):
        exclusion = get_object_or_404(Exclusion, md5=md5)
        sorteo = get_object_or_404(Sorteo,md5=exclusion.sorteo.md5)
        if exclusion:
            exclusion.delete()
            sorteo.done = False
            sorteo.enviado = False
            sorteo.save()
            log_msg = "Exclusion de {} a {} borrada por {} de evento {}".format(exclusion.de_participante, exclusion.a_participante, self.request.user,sorteo.name)
            logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:detail',kwargs={'md5':sorteo.md5} ))


class BorrarSorteoView(LoginRequiredMixin, generic.View):

    def get(self, request, md5):
        sorteo = get_object_or_404(Sorteo, md5=md5)
        if sorteo:
            sorteo.delete()
            log_msg = "Evento {} eliminado por {}".format(sorteo.name, self.request.user)
            logger.info(log_msg)
        return HttpResponseRedirect(reverse('sorteos:index'))


class RegisterView(generic.View):

    def get(self, request):
        form = RegisterForm()
        ctx = {'form': form, 'version': settings.VERSION}
        return render(request, 'registration/register.html', ctx)

    def post(self, request):
        form = RegisterForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form, 'version': settings.VERSION}
            return render(request, 'registration/register.html', ctx)
        user = form.save(commit=False)
        user.is_active = False
        user.save()
        log_msg = "Usuario {} registrado. Cuenta no activada".format(user)
        logger.info(log_msg)
        current_site = get_current_site(request)
        mail_subject = 'Amigo Invisible - Activa tu cuenta'
        message = render_to_string('registration/acc_active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),

templates/sorteos/about.html
{% extends "sorteos/base_layout.html" %}
{% load static %}

{% block content %}
    <div class="container-sm p-2 my-2">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card">
                    <img src="{% static 'img/regalo.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Card title</h5>
                        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>                           
                    </div>                    
                </div>          
            </div>
        </div>
    </div>
{% endblock %}

templates/sorteos/base_layout.html
{% load static %}

<!doctype html>
<html lang="es">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="{% static 'plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

     <!-- Font Awesome -->
    <link rel="stylesheet" href="{% static 'plugins/fontawesome-free/css/all.min.css' %}">

    <title>Amigo Invisible</title>ç

    <link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}"/>
    
  </head>
  <body>
    <div class="container-fluid">
        <div class="row">
            <nav class="navbar navbar-expand-sm fixed-top navbar-light bg-light">
                <div class="container-fluid">
                  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                  </button>
                  <a class="navbar-brand" href="{% url 'sorteos:landing' %}">Amigo Invisible</a>
                  <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
                    {% if user.is_authenticated %}
                      <ul class="navbar-nav me-auto mb-2 mb-sm-0">
                        <li class="nav-item">
                          <a class="nav-link">Hola, {{user.username}}</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'sorteos:index' %}">Mis eventos</a>
                        </li>
                        {% if user.is_staff %}
                          <li class="nav-item">
                            <a class="nav-link" href="{% url 'admin:index' %}">Administrar</a>
                          </li>
                        {% endif %}
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'password_change' %}">Cambiar contraseña</a>
                        </li>
                        <li class="nav-item">
                          <a class="nav-link" href="{% url 'logout' %}">Salir</a>
                        </li>
                      </ul>
                    {% endif %}
                  </div>
                </div>
              </nav>
        </div>
        
        <div class="row">
            {% block content %}

            {% endblock %}
        </div>
    
        
    <!-- Content Wrapper. Contains page content -->
  
  <!-- /.content-wrapper -->
    </div>
    
    <footer class="main-footer">
        <nav class="navbar fixed-bottom navbar-light bg-light">
            <div class="container-fluid">
              <!-- <div class="float d-none d-sm-inline-block"> -->
                <ul class="list-inline mb-2">
                  <li class="list-inline-item"><a href="#">Protección de datos</a></li>
                  <li class="list-inline-item">·</li>
                  <li class="list-inline-item"><a href="#">Aviso legal</a></li>
                  <li class="list-inline-item">·</li>
                  <li class="list-inline-item"><b>Version</b> {{ version }}</li>
                  
                  <!-- <li class="list-inline-item"><strong>Diseñado con <a href="https://www.python.org/">Python</a> y <a href="https://https://www.djangoproject.com/">Django</a>.</strong></li> -->
                </ul>
              <!-- </div>  -->
            </div>
          </nav>
      </footer>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static 'plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

templates/sorteos/detail.html
{% extends "sorteos/base_layout.html" %}
{% load static %}

{% block content %}
    <div class="container-sm pt-5">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">        
                        <div class="box">
                            <div class="box-header with-border">
                                <div class="col-6">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'sorteos:participante' sorteo.md5%}">Añadir amigo</a></li>
                                            {% if sorteo.done %}
                                            <li class="breadcrumb-item active" aria-current="page">Sortear</li>
                                            <li class="breadcrumb-item"><a href="{% url 'sorteos:mails' sorteo.md5%}" >Informar amigos</a></li>
                                            {% else %}
                                            <li class="breadcrumb-item"><a href="{% url 'sorteos:sortear' sorteo.md5%}">Sortear</a></li>
                                            <li class="breadcrumb-item active" aria-current="page">Informar amigos</li>
                                            {% endif %}
                                            <!-- <li class="breadcrumb-item"><a href="{% url 'sorteos:index' %}">Mis eventos</a></li> -->
                                        </ol>
                                    </nav>
                                </div>
                                <div class="col-6">
                                    <h3 class="box-title"> Amigos en {{sorteo.name}} </h3>
                                </div>                                    
                            </div>        
                            <div class="box-body">
                                <div class="row">
                                    {% if sorteo.done and sorteo.enviado %}
                                    <div class="alert alert-danger" role="alert">¡Ojo, el sorteo ya está hecho y has enviado la información a los participantes!<br>Si haces cambios, deberás volver a sortear y enviar información a los participantes.<br>Si alguno de los participantes no ha recibido el email, pídele que compruebe su carpeta de SPAM.<br>También puedes volver a enviarlos pulsando "Informar amigos". </div>
                                    {% elif sorteo.done and not sorteo.enviado %}
                                    <div class="alert alert-info" role="alert">¡Ya has hecho el sorteo! Envía los resultados a los participantes pulsando "Informar amigos"</div>
                                    {% else %}
                                    <div class="alert alert-dark" role="alert">Si no desear participar en el sorteo, elimínate de la lista de participantes.</div>
                                    <div class="alert alert-dark" role="alert">Cuando termines de añadir participantes y las exclusiones. Pulsa "Sortear".</div>                                          
                                    {% endif %}
                                </div>
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Participante</th>
                                                <th class="text-center">Email</th>
                                                <th class="text-center">Excepto</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for amigo in sorteo_participantes_list %}
                                            <tr>
                                                <td align="center">
                                                    {{ amigo.name }} 
                                                    <a href="{% url 'sorteos:participanteborrar' amigo.md5 %}"><i class="fas fa-trash"></i></a>
                                                </td>
                                                <td align="center">
                                                    {{ amigo.email }}
                                                </td>
                                                <td align="center">
                                                    {% for e in exclusiones %}
                                                        {% if e.de_participante == amigo %}
                                                            {{ e.a_participante }}
                                                            <a href="{% url 'sorteos:exclusionborrar' e.md5%}"><i class="fas fa-trash"></i></a>
                                                        {% endif %}
                                                    {% endfor %}
                                                    <a href="{% url 'sorteos:exclusion' sorteo.md5 amigo.md5 %}"><i class="fas fa-plus"></i></a>                                          
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>                                                      
                                    </table>                      
                                </div>
                                <a class="btn btn-primary btn-block" href="{% url 'sorteos:participante' sorteo.md5%}" role="button">Añadir amigo</a>
                                <a class="btn btn-primary btn-block {% if sorteo.done %}disabled{% endif %}" href="{% url 'sorteos:sortear' sorteo.md5%}" role="button">Sortear</a>
                                <a class="btn btn-primary btn-block {% if not sorteo.done %}disabled{% endif %}" href="{% url 'sorteos:mails' sorteo.md5%}" role="button">Informar amigos</a>
                                </div>       
                            </div>
                            <!-- /.box-body -->
                        </div>        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/sorteos/index.html
{% extends "sorteos/base_layout.html" %}
{% load static %}

{% block content %}
    <!-- Main content -->
    <div class="container-sm pt-5">
        <div class="row">
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">        
                        <div class="box">
                            <div class="box-header with-border">
                                <div class="col-6">
                                    <nav aria-label="breadcrumb">
                                        <ol class="breadcrumb">
                                            <li class="breadcrumb-item"><a href="{% url 'sorteos:sorteo' %}">Nuevo evento</a></li>
                                        </ol>
                                    </nav>
                                </div>
                                <div class="col-6">
                                    <h3 class="box-title"> Mis eventos </h3>
                                </div>                                
                            </div>        
                            <div class="box-body">
                                <div class="table-responsive">
                                    <table class="table table-bordered table-hover table-striped">
                                        <thead>
                                            <tr>
                                                <th class="text-center">Evento</th>
                                                <th class="text-center">Condiciones</th>
                                                <th class="text-center"">Fecha</th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            {% for sorteo in user_sorteos_list %}
                                            <tr>
                                                <td align="center">
                                                    <a href="{% url 'sorteos:detail' sorteo.md5 %}">{{ sorteo.name }}</a>
                                                    <a href="{% url 'sorteos:sorteoborrar' sorteo.md5 %}"><i class="fas fa-trash"></i></a>
                                                </td>
                                                <td align="center">
                                                    {{ sorteo.description }}
                                                </td>
                                                <td align="center">
                                                    {{ sorteo.created }}
                                                </td>
                                            </tr>
                                            {% endfor %}
                                        </tbody>                                                      
                                    </table>                        
                                </div>        
                            </div>
                            <!-- /.box-body -->
                        </div>        
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/sorteos/landing.html
{% extends "sorteos/base_layout.html" %}
{% load static %}

{% block content %}
    <div class="container-sm p-2 my-2">
        <div class="row justify-content-center">
            <div class="col-lg-8">
                <div class="card text-center">
                    <img src="{% static 'img/regalo.png' %}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">Amigo Invisible</h5>
                        <p class="card-text">Sorteos de amigo invisible de forma segura y respetuosa con tu privacida.</p>
                        <a class="btn btn-primary" href="{% url 'sorteos:index' %}" role="button">Comienza ahora</a>                           
                    </div>                    
                </div>          
            </div>
        </div>
    </div>
{% endblock %}